language: python

python:
  - 2.6
  - 2.7
  - 3.3

before_install:
  - pip install --use-mirrors PyYAML SQLAlchemy 'Tornado<2.0'

install:
  - python setup.py install
  - pip install catbox

script:
  - bin/testify test -x fake
